# Datasource
quarkus.datasource.db-kind=mssql
quarkus.datasource.username=broker_user
quarkus.datasource.password=Jm6!Qp4$XzN3
#quarkus.datasource.jdbc.url=jdbc:sqlserver://35.223.215.217:1433;databaseName=kwality_broker;encrypt=true;trustServerCertificate=true;
quarkus.datasource.jdbc.url=jdbc:sqlserver://localhost:1433;databaseName=kwality_broker;encrypt=true;trustServerCertificate=true;

# Hibernate ORM
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.database.generation=update

# Optional
quarkus.datasource.jdbc.max-size=8
quarkus.datasource.jdbc.min-size=2

# Gera a specification OpenAPI
quarkus.smallrye-openapi.path=/openapi
# Ativa Swagger UI
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui



